server:
  port: 8004
spring:
  profiles:
    active:
    - dev
    - druid

#logging:
#  config: classpath:log4j2.xml

mybatis-plus:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.wang.pojo
